site_name: Sway 🌴 - Version FR
theme: readthedocs
nav:
  - Accueil: index.md
  - Introduction:
    - Introduction: introduction/introduction.md
    - Démarrage: introduction/demarrage.md
    - Installation: introduction/installation.md
    - La toolchain Fuel: introduction/toolchainFuel.md
    - Mon premier projet: introduction/forcProject.md
  - Exemples:
    - Counter: examples/counter.md
    - Subcurrency: examples/subcurrency.md
    - Fizzbuzz: examples/fizzbuzz.md
    - Wallet Smart Contract: examples/wallet-smart-contract.md
  - Types de programmes:
    - Contrats: program-type/contrats.md
    - Bibliotheque: program-type/bibliotheque.md
    - Scripts: program-type/scripts.md
    - Prédicats: program-type/predicats.md